FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ cmake linux-headers bluez git pkgconfig dbus-dev

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--host"]
